checking fio existent on setup
Signed-off-by: Satoru Takeuchi <satoru.takeuchi@gmail.com>

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,3 +1,7 @@
 #!/bin/bash
 
+if ! (which fio) >/dev/null ; then
+    echo "fio is not found. it should be installed to run fsperf" >&2
+    exit 1
+fi
 cat fsperf-sqlite.sql | sqlite3 fsperf-results.db
